# Generated by Django 5.2.5 on 2025-08-17 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expenselimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenselimit',
            name='monthly_expense_limit',
            field=models.IntegerField(default=0),
        ),
    ]
